# Special tokens
BEGIN_SEARCH_QUERY = "<begin_search_query>"
END_SEARCH_QUERY = "</end_search_query>"
BEGIN_SEARCH_RESULT = "<begin_search_result>"
END_SEARCH_RESULT = "</end_search_result>"
BEGIN_CODE_QUERY = "<begin_code_query>"
END_CODE_QUERY = "</end_code_query>"
BEGIN_CODE_RESULT = "<begin_code_result>"
END_CODE_RESULT = "</end_code_result>"
BEGIN_MIND_MAP_QUERY = "<begin_mind_map_query>"
END_MIND_MAP_QUERY = "</end_mind_map_query>"
BEGIN_MIND_MAP_RESULT = "<begin_mind_map_result>"
END_MIND_MAP_RESULT = "</end_mind_map_result>"
CHAT_TEMPLATE = "{% for message in messages %}{% if message['role'] == 'user' %}{{ ' ' }}{% endif %}{{ message['content'] }}{% if not loop.last %}{{ ' ' }}{% endif %}{% endfor %}{{ eos_token }}"
